#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XAXIDMA_NUM_INSTANCES 3

/* Definitions for peripheral AXI_DMA_A */
#define XPAR_AXI_DMA_A_COMPATIBLE "xlnx,axi-dma-7.1"
#define XPAR_AXI_DMA_A_BASEADDR 0x41e00000
#define XPAR_AXI_DMA_A_HIGHADDR 0x41e0ffff
#define XPAR_AXI_DMA_A_SG_INCLUDE_STSCNTRL_STRM 0x0
#define XPAR_AXI_DMA_A_INCLUDE_MM2S 0x1
#define XPAR_AXI_DMA_A_INCLUDE_MM2S_DRE 0x0
#define XPAR_AXI_DMA_A_MM2S_DATA_WIDTH 0x20
#define XPAR_AXI_DMA_A_INCLUDE_S2MM 0x0
#define XPAR_AXI_DMA_A_INCLUDE_S2MM_DRE 0x0
#define XPAR_AXI_DMA_A_S2MM_DATA_WIDTH 0x20
#define XPAR_AXI_DMA_A_NUM_MM2S_CHANNELS 0x1
#define XPAR_AXI_DMA_A_NUM_S2MM_CHANNELS 0x1
#define XPAR_AXI_DMA_A_MM2S_BURST_SIZE 0x10
#define XPAR_AXI_DMA_A_S2MM_BURST_SIZE 0x10
#define XPAR_AXI_DMA_A_MICRO_DMA 0x0
#define XPAR_AXI_DMA_A_ADDRWIDTH 0x20
#define XPAR_AXI_DMA_A_SG_LENGTH_WIDTH 0xe

/* Canonical definitions for peripheral AXI_DMA_A */
#define XPAR_XAXIDMA_0_BASEADDR 0x41e00000
#define XPAR_XAXIDMA_0_HIGHADDR 0x41e0ffff
#define XPAR_XAXIDMA_0_ADDRWIDTH 0x20
#define XPAR_XAXIDMA_0_COMPATIBLE "xlnx,axi-dma-7.1"
#define XPAR_XAXIDMA_0_INCLUDE_MM2S 0x1
#define XPAR_XAXIDMA_0_INCLUDE_MM2S_DRE 0x0
#define XPAR_XAXIDMA_0_INCLUDE_S2MM 0x0
#define XPAR_XAXIDMA_0_INCLUDE_S2MM_DRE 0x0
#define XPAR_XAXIDMA_0_MM2S_DATA_WIDTH 0x20
#define XPAR_XAXIDMA_0_MM2S_BURST_SIZE 0x10
#define XPAR_XAXIDMA_0_MICRO_DMA 0x0
#define XPAR_XAXIDMA_0_NUM_MM2S_CHANNELS 0x1
#define XPAR_XAXIDMA_0_NUM_S2MM_CHANNELS 0x1
#define XPAR_XAXIDMA_0_SG_INCLUDE_STSCNTRL_STRM 0x0
#define XPAR_XAXIDMA_0_S2MM_DATA_WIDTH 0x20
#define XPAR_XAXIDMA_0_S2MM_BURST_SIZE 0x10
#define XPAR_XAXIDMA_0_SG_LENGTH_WIDTH 0xe

/* Definitions for peripheral AXI_DMA_B */
#define XPAR_AXI_DMA_B_COMPATIBLE "xlnx,axi-dma-7.1"
#define XPAR_AXI_DMA_B_BASEADDR 0x41e10000
#define XPAR_AXI_DMA_B_HIGHADDR 0x41e1ffff
#define XPAR_AXI_DMA_B_SG_INCLUDE_STSCNTRL_STRM 0x0
#define XPAR_AXI_DMA_B_INCLUDE_MM2S 0x1
#define XPAR_AXI_DMA_B_INCLUDE_MM2S_DRE 0x0
#define XPAR_AXI_DMA_B_MM2S_DATA_WIDTH 0x20
#define XPAR_AXI_DMA_B_INCLUDE_S2MM 0x0
#define XPAR_AXI_DMA_B_INCLUDE_S2MM_DRE 0x0
#define XPAR_AXI_DMA_B_S2MM_DATA_WIDTH 0x20
#define XPAR_AXI_DMA_B_NUM_MM2S_CHANNELS 0x1
#define XPAR_AXI_DMA_B_NUM_S2MM_CHANNELS 0x1
#define XPAR_AXI_DMA_B_MM2S_BURST_SIZE 0x10
#define XPAR_AXI_DMA_B_S2MM_BURST_SIZE 0x10
#define XPAR_AXI_DMA_B_MICRO_DMA 0x0
#define XPAR_AXI_DMA_B_ADDRWIDTH 0x20
#define XPAR_AXI_DMA_B_SG_LENGTH_WIDTH 0xe

/* Canonical definitions for peripheral AXI_DMA_B */
#define XPAR_XAXIDMA_1_BASEADDR 0x41e10000
#define XPAR_XAXIDMA_1_HIGHADDR 0x41e1ffff
#define XPAR_XAXIDMA_1_ADDRWIDTH 0x20
#define XPAR_XAXIDMA_1_COMPATIBLE "xlnx,axi-dma-7.1"
#define XPAR_XAXIDMA_1_INCLUDE_MM2S 0x1
#define XPAR_XAXIDMA_1_INCLUDE_MM2S_DRE 0x0
#define XPAR_XAXIDMA_1_INCLUDE_S2MM 0x0
#define XPAR_XAXIDMA_1_INCLUDE_S2MM_DRE 0x0
#define XPAR_XAXIDMA_1_MM2S_DATA_WIDTH 0x20
#define XPAR_XAXIDMA_1_MM2S_BURST_SIZE 0x10
#define XPAR_XAXIDMA_1_MICRO_DMA 0x0
#define XPAR_XAXIDMA_1_NUM_MM2S_CHANNELS 0x1
#define XPAR_XAXIDMA_1_NUM_S2MM_CHANNELS 0x1
#define XPAR_XAXIDMA_1_SG_INCLUDE_STSCNTRL_STRM 0x0
#define XPAR_XAXIDMA_1_S2MM_DATA_WIDTH 0x20
#define XPAR_XAXIDMA_1_S2MM_BURST_SIZE 0x10
#define XPAR_XAXIDMA_1_SG_LENGTH_WIDTH 0xe

/* Definitions for peripheral AXI_DMA_C */
#define XPAR_AXI_DMA_C_COMPATIBLE "xlnx,axi-dma-7.1"
#define XPAR_AXI_DMA_C_BASEADDR 0x41e20000
#define XPAR_AXI_DMA_C_HIGHADDR 0x41e2ffff
#define XPAR_AXI_DMA_C_SG_INCLUDE_STSCNTRL_STRM 0x0
#define XPAR_AXI_DMA_C_INCLUDE_MM2S 0x0
#define XPAR_AXI_DMA_C_INCLUDE_MM2S_DRE 0x0
#define XPAR_AXI_DMA_C_MM2S_DATA_WIDTH 0x20
#define XPAR_AXI_DMA_C_INCLUDE_S2MM 0x1
#define XPAR_AXI_DMA_C_INCLUDE_S2MM_DRE 0x0
#define XPAR_AXI_DMA_C_S2MM_DATA_WIDTH 0x20
#define XPAR_AXI_DMA_C_NUM_MM2S_CHANNELS 0x1
#define XPAR_AXI_DMA_C_NUM_S2MM_CHANNELS 0x1
#define XPAR_AXI_DMA_C_MM2S_BURST_SIZE 0x10
#define XPAR_AXI_DMA_C_S2MM_BURST_SIZE 0x10
#define XPAR_AXI_DMA_C_MICRO_DMA 0x0
#define XPAR_AXI_DMA_C_ADDRWIDTH 0x20
#define XPAR_AXI_DMA_C_SG_LENGTH_WIDTH 0xe

/* Canonical definitions for peripheral AXI_DMA_C */
#define XPAR_XAXIDMA_2_BASEADDR 0x41e20000
#define XPAR_XAXIDMA_2_HIGHADDR 0x41e2ffff
#define XPAR_XAXIDMA_2_ADDRWIDTH 0x20
#define XPAR_XAXIDMA_2_COMPATIBLE "xlnx,axi-dma-7.1"
#define XPAR_XAXIDMA_2_INCLUDE_MM2S 0x0
#define XPAR_XAXIDMA_2_INCLUDE_MM2S_DRE 0x0
#define XPAR_XAXIDMA_2_INCLUDE_S2MM 0x1
#define XPAR_XAXIDMA_2_INCLUDE_S2MM_DRE 0x0
#define XPAR_XAXIDMA_2_MM2S_DATA_WIDTH 0x20
#define XPAR_XAXIDMA_2_MM2S_BURST_SIZE 0x10
#define XPAR_XAXIDMA_2_MICRO_DMA 0x0
#define XPAR_XAXIDMA_2_NUM_MM2S_CHANNELS 0x1
#define XPAR_XAXIDMA_2_NUM_S2MM_CHANNELS 0x1
#define XPAR_XAXIDMA_2_SG_INCLUDE_STSCNTRL_STRM 0x0
#define XPAR_XAXIDMA_2_S2MM_DATA_WIDTH 0x20
#define XPAR_XAXIDMA_2_S2MM_BURST_SIZE 0x10
#define XPAR_XAXIDMA_2_SG_LENGTH_WIDTH 0xe

#define XPAR_XAXIPMON_NUM_INSTANCES 1

/* Definitions for peripheral AXI_PERF_MON_0 */
#define XPAR_AXI_PERF_MON_0_COMPATIBLE "xlnx,axi-perf-mon-5.0"
#define XPAR_AXI_PERF_MON_0_BASEADDR 0x44a10000
#define XPAR_AXI_PERF_MON_0_HIGHADDR 0x44a1ffff
#define XPAR_AXI_PERF_MON_0_GLOBAL_COUNT_WIDTH 0x20
#define XPAR_AXI_PERF_MON_0_METRICS_SAMPLE_COUNT_WIDTH 0x20
#define XPAR_AXI_PERF_MON_0_ENABLE_EVENT_COUNT 0x1
#define XPAR_AXI_PERF_MON_0_NUM_MONITOR_SLOTS 0x1
#define XPAR_AXI_PERF_MON_0_NUM_OF_COUNTERS 0x1
#define XPAR_AXI_PERF_MON_0_HAVE_SAMPLED_METRIC_CNT 0x1
#define XPAR_AXI_PERF_MON_0_ENABLE_EVENT_LOG 0x0
#define XPAR_AXI_PERF_MON_0_FIFO_AXIS_DEPTH 0x20
#define XPAR_AXI_PERF_MON_0_FIFO_AXIS_TDATA_WIDTH 0x38
#define XPAR_AXI_PERF_MON_0_FIFO_AXIS_TID_WIDTH 0x1
#define XPAR_AXI_PERF_MON_0_METRIC_COUNT_SCALE 0x1
#define XPAR_AXI_PERF_MON_0_ENABLE_ADVANCED 0x1
#define XPAR_AXI_PERF_MON_0_ENABLE_PROFILE 0x0
#define XPAR_AXI_PERF_MON_0_ENABLE_TRACE 0x0

/* Canonical definitions for peripheral AXI_PERF_MON_0 */
#define XPAR_XAXIPMON_0_BASEADDR 0x44a10000
#define XPAR_XAXIPMON_0_HIGHADDR 0x44a1ffff
#define XPAR_XAXIPMON_0_COMPATIBLE "xlnx,axi-perf-mon-5.0"
#define XPAR_XAXIPMON_0_ENABLE_EVENT_COUNT 0x1
#define XPAR_XAXIPMON_0_ENABLE_EVENT_LOG 0x0
#define XPAR_XAXIPMON_0_ENABLE_ADVANCED 0x1
#define XPAR_XAXIPMON_0_ENABLE_PROFILE 0x0
#define XPAR_XAXIPMON_0_ENABLE_TRACE 0x0
#define XPAR_XAXIPMON_0_FIFO_AXIS_DEPTH 0x20
#define XPAR_XAXIPMON_0_FIFO_AXIS_TDATA_WIDTH 0x38
#define XPAR_XAXIPMON_0_FIFO_AXIS_TID_WIDTH 0x1
#define XPAR_XAXIPMON_0_GLOBAL_COUNT_WIDTH 0x20
#define XPAR_XAXIPMON_0_HAVE_SAMPLED_METRIC_CNT 0x1
#define XPAR_XAXIPMON_0_METRICS_SAMPLE_COUNT_WIDTH 0x20
#define XPAR_XAXIPMON_0_METRIC_COUNT_SCALE 0x1
#define XPAR_XAXIPMON_0_NUM_MONITOR_SLOTS 0x1
#define XPAR_XAXIPMON_0_NUM_OF_COUNTERS 0x1

#define XPAR_XBRAM_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_BASEADDR 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_HIGHADDR 0x7fff
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_DATA_WIDTH 0x20
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_FAULT_INJECT 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_CE_FAILING_REGISTERS 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_UE_FAILING_REGISTERS 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_REGISTER 0x0
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR_WRITE_ACCESS 0x2

/* Canonical definitions for peripheral MICROBLAZE_RISCV_0_LOCAL_MEMORY_DLMB_BRAM_IF_CNTLR */
#define XPAR_XBRAM_0_BASEADDR 0x0
#define XPAR_XBRAM_0_HIGHADDR 0x7fff
#define XPAR_XBRAM_0_COMPATIBLE "xlnx,lmb-bram-if-cntlr-4.0"
#define XPAR_XBRAM_0_CE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_DATA_WIDTH 0x20
#define XPAR_XBRAM_0_ECC 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_REGISTER 0x0
#define XPAR_XBRAM_0_ECC_ONOFF_RESET_VALUE 0x1
#define XPAR_XBRAM_0_FAULT_INJECT 0x0
#define XPAR_XBRAM_0_UE_FAILING_REGISTERS 0x0
#define XPAR_XBRAM_0_WRITE_ACCESS 0x2

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x2580
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define XPAR_XUARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x2580
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

/* Definitions for peripheral ACCELERATOR_STREAM_0 */
#define XPAR_ACCELERATOR_STREAM_0_BASEADDR 0x44a00000
#define XPAR_ACCELERATOR_STREAM_0_HIGHADDR 0x44a0ffff

/*  BOARD definition */
#define XPS_BOARD_NEXYS4_DDR

#define XPAR_MIG_0_BASEADDRESS 0x80000000
#define XPAR_MIG_0_HIGHADDRESS 0x87ffffff
#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x7fff

/*  CPU parameters definition */
#define XPAR_MICROBLAZE_RISCV_TIMEBASE_FREQUENCY 100000000
#define XPAR_MICROBLAZE_RISCV_FREQ 100000000
#define XPAR_MICROBLAZE_RISCV_BASE_VECTORS 0
#define XPAR_MICROBLAZE_RISCV_USE_MMU 0
#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 1
#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 1
#define XPAR_MICROBLAZE_RISCV_USE_MULDIV 0
#define XPAR_MICROBLAZE_RISCV_USE_ATOMIC 0
#define XPAR_MICROBLAZE_RISCV_USE_FPU 0
#define XPAR_MICROBLAZE_RISCV_DATA_SIZE 32
#define XPAR_MICROBLAZE_RISCV_D_CACHE_SIZE 8192
#define XPAR_MICROBLAZE_RISCV_D_CACHE_LINE_SIZE 16
#define XPAR_MICROBLAZE_RISCV_DCACHE_USE_WRITEBACK 0
#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_D_CACHE_BASEADDR 1151336448
#define XPAR_MICROBLAZE_RISCV_D_CACHE_HIGHADDR 1151401983
#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4
#define XPAR_MICROBLAZE_RISCV_REG 0

#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000

#define XPAR_MICROBLAZE_RISCV_USE_DCACHE 1

#define XPAR_MICROBLAZE_RISCV_DCACHE_LINE_LEN 4

#define XPAR_MICROBLAZE_RISCV_DCACHE_BYTE_SIZE 8192

#define XPAR_MICROBLAZE_RISCV_USE_ICACHE 1

#define XPAR_MICROBLAZE_RISCV_ICACHE_LINE_LEN 4

#define XPAR_MICROBLAZE_RISCV_ICACHE_BYTE_SIZE 8192

#define XPAR_MICROBLAZE_RISCV_USE_FPU 0

#define XPAR_MICROBLAZE_RISCV_USE_MMU 0

#define XPAR_MICROBLAZE_RISCV_USE_SLEEP 0

#define XPAR_MICROBLAZE_RISCV_FAULT_TOLERANT 0

#define XPAR_MICROBLAZE_RISCV_D_LMB 1

#define XPAR_MICROBLAZE_RISCV_USE_BRANCH_TARGET_CACHE 0

#define XPAR_MICROBLAZE_RISCV_BRANCH_TARGET_CACHE_SIZE 0

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7a100t"

#endif  /* end of protection macro */