domain_path: C:\Accelerator_System_with_APM\APM_AXI_FINALII\export\APM_AXI_FINALII\sw\standalone_microblaze_riscv_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
